const Animals = [
  { name: "Dog", price: 500, category: "Mammal", alt_description: "Dog" },
  { name: "Cat", price: 200, category: "Mammal", alt_description: "Cat" },
  { name: "Rabbit", price: 150, category: "Mammal", alt_description: "Rabbit" },
  {
    name: "Guinea Pig",
    price: 50,
    category: "Mammal",
    alt_description: "Guinea Pig",
  },
  { name: "Ferret", price: 150, category: "Mammal", alt_description: "Ferret" },
  {
    name: "Betta Fish",
    price: 10,
    category: "Aquatic",
    alt_description: "Betta Fish",
  },
  {
    name: "Goldfish",
    price: 5,
    category: "Aquatic",
    alt_description: "Goldfish",
  },
  {
    name: "Tropical Fish",
    price: 30,
    category: "Aquatic",
    alt_description: "Tropical Fish",
  },
  {
    name: "African Dwarf Frog",
    price: 10,
    category: "Aquatic",
    alt_description: "African Dwarf Frog",
  },
  {
    name: "Hermit Crab",
    price: 20,
    category: "Aquatic",
    alt_description: "Hermit Crab",
  },
  { name: "Owl", price: 350, category: "Nocturnal", alt_description: "Owl" },
  {
    name: "Sugar Glider",
    price: 150,
    category: "Nocturnal",
    alt_description: "Sugar Glider",
  },
  {
    name: "Hedgehog",
    price: 100,
    category: "Nocturnal",
    alt_description: "Hedgehog",
  },
  { name: "Bat", price: 250, category: "Nocturnal", alt_description: "Bat" },
  {
    name: "Lemur",
    price: 2200,
    category: "Nocturnal",
    alt_description: "Lemur",
  },
  { name: "Gecko", price: 50, category: "Reptile", alt_description: "Gecko" },
  {
    name: "Bearded Dragon",
    price: 70,
    category: "Reptile",
    alt_description: "Bearded Dragon",
  },
  {
    name: "Leopard Gecko",
    price: 50,
    category: "Reptile",
    alt_description: "Leopard Gecko",
  },
  {
    name: "Ball Python",
    price: 100,
    category: "Reptile",
    alt_description: "Ball Python",
  },
  {
    name: "Tortoise",
    price: 200,
    category: "Reptile",
    alt_description: "Tortoise",
  },
];
