import "../img/D";
export const Animals = [
  {
    name: "Dog",
    price: 500,
    category: "Mammal",
    alt_description: "Dog",
    img_url: "img/dog.avif",
  },
  {
    name: "Cat",
    price: 200,
    category: "Mammal",
    alt_description: "Cat",
    img_url: "img/cat.avif",
  },
  {
    name: "Rabbit",
    price: 150,
    category: "Mammal",
    alt_description: "Rabbit",
    img_url: "x",
  },
  {
    name: "Guinea Pig",
    price: 50,
    category: "Mammal",
    alt_description: "Guinea Pig",
    img_url: "x",
  },
  {
    name: "Ferret",
    price: 150,
    category: "Mammal",
    alt_description: "Ferret",
    img_url: "x",
  },
  {
    name: "Betta Fish",
    price: 10,
    category: "Aquatic",
    alt_description: "Betta Fish",
    img_url: "x",
  },
  {
    name: "Goldfish",
    price: 5,
    category: "Aquatic",
    alt_description: "Goldfish",
    img_url: "x",
  },
  {
    name: "Tropical Fish",
    price: 30,
    category: "Aquatic",
    alt_description: "Tropical Fish",
    img_url: "x",
  },
  {
    name: "African Dwarf Frog",
    price: 10,
    category: "Aquatic",
    alt_description: "African Dwarf Frog",
    img_url: "x",
  },
  {
    name: "Hermit Crab",
    price: 20,
    category: "Aquatic",
    alt_description: "Hermit Crab",
    img_url: "x",
  },
  {
    name: "Owl",
    price: 350,
    category: "Nocturnal",
    alt_description: "Owl",
    img_url: "x",
  },
  {
    name: "Sugar Glider",
    price: 150,
    category: "Nocturnal",
    alt_description: "Sugar Glider",
    img_url: "x",
  },
  {
    name: "Hedgehog",
    price: 100,
    category: "Nocturnal",
    alt_description: "Hedgehog",
    img_url: "x",
  },
  {
    name: "Bat",
    price: 250,
    category: "Nocturnal",
    alt_description: "Bat",
    img_url: "x",
  },
  {
    name: "Lemur",
    price: 2200,
    category: "Nocturnal",
    alt_description: "Lemur",
    img_url: "x",
  },
  {
    name: "Gecko",
    price: 50,
    category: "Reptile",
    alt_description: "Gecko",
    img_url: "x",
  },
  {
    name: "Bearded Dragon",
    price: 70,
    category: "Reptile",
    alt_description: "Bearded Dragon",
    img_url: "x",
  },
  {
    name: "Leopard Gecko",
    price: 50,
    category: "Reptile",
    alt_description: "Leopard Gecko",
    img_url: "x",
  },
  {
    name: "Ball Python",
    price: 100,
    category: "Reptile",
    alt_description: "Ball Python",
    img_url: "x",
  },
  {
    name: "Tortoise",
    price: 200,
    category: "Reptile",
    alt_description: "Tortoise",
    img_url: "x",
  },
];
